## 실습 과제1: NumPy를 활용한 행렬 변형 실습
### 문제 1: 난수 행렬 생성
N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.

In [28]:
import numpy as np

In [29]:
N, M = 6, 5
A = np.array([np.random.rand() for _ in range(N * M)])
A = A.reshape((N, M))
# A = np.random.random((N, M))
A

array([[0.33001713, 0.97960202, 0.76728699, 0.08952685, 0.48227822],
       [0.46289615, 0.47484708, 0.68147691, 0.59053027, 0.49312402],
       [0.02746279, 0.63805618, 0.56315562, 0.35712118, 0.15864334],
       [0.37947032, 0.00115785, 0.55220955, 0.5472823 , 0.19543703],
       [0.38890311, 0.04210756, 0.56370083, 0.44861209, 0.27490776],
       [0.85843737, 0.90153452, 0.66602858, 0.78378139, 0.70726437]])

### 문제 2: 새로운 축 추가
행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

In [30]:
B = A[:, np.newaxis, :]
print(B)
B.shape

[[[0.33001713 0.97960202 0.76728699 0.08952685 0.48227822]]

 [[0.46289615 0.47484708 0.68147691 0.59053027 0.49312402]]

 [[0.02746279 0.63805618 0.56315562 0.35712118 0.15864334]]

 [[0.37947032 0.00115785 0.55220955 0.5472823  0.19543703]]

 [[0.38890311 0.04210756 0.56370083 0.44861209 0.27490776]]

 [[0.85843737 0.90153452 0.66602858 0.78378139 0.70726437]]]


(6, 1, 5)

### 문제 3: 슬라이싱을 이용한 특정 요소 변경
행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

In [31]:
B2 = B[2:3, :, :]
B2[:] = 0.3 #사본아니고 뷰를 제공
print(B)

[[[0.33001713 0.97960202 0.76728699 0.08952685 0.48227822]]

 [[0.46289615 0.47484708 0.68147691 0.59053027 0.49312402]]

 [[0.3        0.3        0.3        0.3        0.3       ]]

 [[0.37947032 0.00115785 0.55220955 0.5472823  0.19543703]]

 [[0.38890311 0.04210756 0.56370083 0.44861209 0.27490776]]

 [[0.85843737 0.90153452 0.66602858 0.78378139 0.70726437]]]


### 문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

In [32]:
C = A[np.newaxis, :, :]
D = A[:, : , np.newaxis]
print(C)
print(D)

[[[0.33001713 0.97960202 0.76728699 0.08952685 0.48227822]
  [0.46289615 0.47484708 0.68147691 0.59053027 0.49312402]
  [0.3        0.3        0.3        0.3        0.3       ]
  [0.37947032 0.00115785 0.55220955 0.5472823  0.19543703]
  [0.38890311 0.04210756 0.56370083 0.44861209 0.27490776]
  [0.85843737 0.90153452 0.66602858 0.78378139 0.70726437]]]
[[[0.33001713]
  [0.97960202]
  [0.76728699]
  [0.08952685]
  [0.48227822]]

 [[0.46289615]
  [0.47484708]
  [0.68147691]
  [0.59053027]
  [0.49312402]]

 [[0.3       ]
  [0.3       ]
  [0.3       ]
  [0.3       ]
  [0.3       ]]

 [[0.37947032]
  [0.00115785]
  [0.55220955]
  [0.5472823 ]
  [0.19543703]]

 [[0.38890311]
  [0.04210756]
  [0.56370083]
  [0.44861209]
  [0.27490776]]

 [[0.85843737]
  [0.90153452]
  [0.66602858]
  [0.78378139]
  [0.70726437]]]


### 문제 5: 슬라이싱을 통해 부분 행렬 변경
행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.

In [34]:
D[:2:-1, : , :] = 0.8
print(D)

[[[0.33001713]
  [0.97960202]
  [0.76728699]
  [0.08952685]
  [0.48227822]]

 [[0.46289615]
  [0.47484708]
  [0.68147691]
  [0.59053027]
  [0.49312402]]

 [[0.3       ]
  [0.3       ]
  [0.3       ]
  [0.3       ]
  [0.3       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]]
