## 실습 과제1: NumPy를 활용한 행렬 변형 실습
### 문제 1: 난수 행렬 생성
N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.

In [1]:
import numpy as np

help(np.random.rand)

Help on method rand in module numpy.random.mtrand:

rand(*args) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.rand

In [ ]:
## with
np.random.random()

In [6]:
def desc(A):
  print(A.shape, A.size, A.dtype)

In [10]:
def desc2(A):
  print(np.min(A), np.max(A), np.sum(A), np.mean(A), np.std(A))

In [11]:
N, M = 6, 5
# A = np.array([np.random.rand() for _ in range(N * M)])
# A = A.reshape((N, M))
# A = np.random.random((N, M))
A = np.random.rand(N, M)
A
#데이터 수가 아주 많아질 수 있기 때문에 아래와 같이 나타내자
desc(A)
desc2(A)

(6, 5) 30 float64
0.06984762946102674 0.9983106109829315 17.63211145578212 0.5877370485260707 0.27528002233088095


### 문제 2: 새로운 축 추가
행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

In [12]:
B = A.reshape(1, 6, 1, 1, 5)
desc(B)

(1, 6, 1, 1, 5) 30 float64


In [13]:
B = A[:, np.newaxis, :]
# B = A.reshape(6, 1, 5)
# B = A[:, None, :]
print(B)
B.shape

[[[0.62096381 0.22894858 0.70128852 0.99831061 0.55847207]]

 [[0.66695725 0.57402442 0.36701152 0.15992599 0.50043268]]

 [[0.8474886  0.59583203 0.77523947 0.3894421  0.76652293]]

 [[0.27940584 0.75537239 0.95455347 0.10914243 0.55643618]]

 [[0.89166498 0.7358952  0.78652621 0.95249818 0.81309716]]

 [[0.09840438 0.97692217 0.54903023 0.35245445 0.06984763]]]


(6, 1, 5)

### 문제 3: 슬라이싱을 이용한 특정 요소 변경
행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

In [ ]:
B[2, :] = 0.3
# B2 = B[2, :, :]
# B2[:] = 0.3 #사본아니고 뷰를 제공
print(B)

[[[0.62096381 0.22894858 0.70128852 0.99831061 0.55847207]]

 [[0.66695725 0.57402442 0.36701152 0.15992599 0.50043268]]

 [[0.3        0.3        0.3        0.3        0.3       ]]

 [[0.27940584 0.75537239 0.95455347 0.10914243 0.55643618]]

 [[0.89166498 0.7358952  0.78652621 0.95249818 0.81309716]]

 [[0.09840438 0.97692217 0.54903023 0.35245445 0.06984763]]]


### 문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

In [15]:
C = A[np.newaxis, :, :]
D = A[:, : , np.newaxis]
desc(C)
print(C)
desc(D)
print(D)

(1, 6, 5) 30 float64
[[[0.62096381 0.22894858 0.70128852 0.99831061 0.55847207]
  [0.66695725 0.57402442 0.36701152 0.15992599 0.50043268]
  [0.3        0.3        0.3        0.3        0.3       ]
  [0.27940584 0.75537239 0.95455347 0.10914243 0.55643618]
  [0.89166498 0.7358952  0.78652621 0.95249818 0.81309716]
  [0.09840438 0.97692217 0.54903023 0.35245445 0.06984763]]]
(6, 5, 1) 30 float64
[[[0.62096381]
  [0.22894858]
  [0.70128852]
  [0.99831061]
  [0.55847207]]

 [[0.66695725]
  [0.57402442]
  [0.36701152]
  [0.15992599]
  [0.50043268]]

 [[0.3       ]
  [0.3       ]
  [0.3       ]
  [0.3       ]
  [0.3       ]]

 [[0.27940584]
  [0.75537239]
  [0.95455347]
  [0.10914243]
  [0.55643618]]

 [[0.89166498]
  [0.7358952 ]
  [0.78652621]
  [0.95249818]
  [0.81309716]]

 [[0.09840438]
  [0.97692217]
  [0.54903023]
  [0.35245445]
  [0.06984763]]]


### 문제 5: 슬라이싱을 통해 부분 행렬 변경
행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.

In [ ]:
# D[3: , : , :] = 0.8
D[:2:-1, : , :] = 0.8
print(D)

[[[0.33001713]
  [0.97960202]
  [0.76728699]
  [0.08952685]
  [0.48227822]]

 [[0.46289615]
  [0.47484708]
  [0.68147691]
  [0.59053027]
  [0.49312402]]

 [[0.3       ]
  [0.3       ]
  [0.3       ]
  [0.3       ]
  [0.3       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]

 [[0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]
  [0.8       ]]]
