In [1]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [2]:
len??

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [4]:
l = [1, 2, 3, 4, 5]
l

[1, 2, 3, 4, 5]

In [7]:
%pwd

'D:\\jupyter\\notebook'

In [18]:
!pwd

'pwd'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [21]:
%ls

 D 드라이브의 볼륨: 새 볼륨
 볼륨 일련 번호: 5289-7EFD

 D:\jupyter\notebook 디렉터리

2024-11-12  오전 11:00    <DIR>          .
2024-11-12  오전 11:00    <DIR>          ..
2024-11-12  오전 10:54    <DIR>          .ipynb_checkpoints
2024-11-12  오전 11:00    <DIR>          AIProgramming
2024-11-12  오전 10:54               139 myscript.py
2024-11-12  오전 11:00            24,337 Untitled.ipynb
               2개 파일              24,476 바이트
               4개 디렉터리  1,959,394,562,048 바이트 남음


In [16]:
%run myscript.py

1 의 제곱은  1
2 의 제곱은  4
3 의 제곱은  9


In [17]:
!pip install jupyter

In [20]:
!mkdir AIProgramming

In [29]:
!pip install numpy

  Using cached numpy-2.0.2-cp39-cp39-win_amd64.whl.metadata (59 kB)
Using cached numpy-2.0.2-cp39-cp39-win_amd64.whl (15.9 MB)


In [32]:
import numpy as np
np.__version__

'2.0.2'

In [33]:
l2 = list(range(10))
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
l3 = range(10)
l3

range(0, 10)

In [45]:
l3?

Type:        range
String form: range(0, 10)
Length:      10
Docstring:  
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).

In [40]:
import array
l = list(range(10))
a = array.array('i', l)
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
import numpy as np

In [38]:
#정수 배열
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [41]:
a?

Type:        array
String form: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Length:      10
Docstring:  
array(typecode [, initializer]) -> array

Return a new array whose items are restricted by typecode, and
initialized from the optional initializer value, which must be a list,
string or iterable over elements of the appropriate type.

Arrays represent basic values and behave very much like lists, except
the type of objects stored in them is constrained. The type is specified
at object creation time by using a type code, which is a single character.
The following type codes are defined:

    Type code   C Type             Minimum size in bytes
    'b'         signed integer     1
    'B'         unsigned integer   1
    'u'         Unicode character  2 (see note)
    'h'         signed integer     2
    'H'         unsigned integer   2
    'i'         signed integer     2
    'I'         unsigned integer   2
    'l'         signed integer     4
    'L'         unsigned integer   4
   

In [42]:
np.array([3.14, 4, 2, 3], dtype='float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [44]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [50]:
np.zeros(10, dtype=int) #zeros 함수 자체가 배열을 반환하는 함수

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [56]:
np.linspace(0, 1, 5) #0 ~ 1 범위에 5게 구간 나누기  linearspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
np.random.normal(0, 1, (3, 3)) #평균, 편차, 3x3행렬로 반환

array([[ 0.75970575,  0.24405076, -1.24655832],
       [ 1.95135141,  0.92675967,  0.97912981],
       [-0.35130063, -1.21634838, -0.34289235]])

In [69]:
np.random.randint(1, 10, (3, 3))

array([[1, 7, 3],
       [5, 7, 6],
       [1, 9, 1]], dtype=int32)

In [78]:
np.random.seed(0) #시드를 설정하면 seed에 따라 값을 랜덤하게 -> seed 안 바꾸면 항상 같은 값
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print('x1 : ', x1)
print('x2 : ', x2)
print('x3 : ', x3)

x1 :  [5 0 3 3 7 9]
x2 :  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3 :  [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [82]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(3, 4)
(3, 4, 5)


In [83]:
x2[-2]

array([7, 6, 8, 8], dtype=int32)

In [87]:
n1 = x2[-2][-1]
n2 = x2[-2, -1]
print(n1, n2)

8 8


In [92]:
print(x1[1:5:2])

[0 3]


In [94]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
x[3:9:2]

array([3, 5, 7])

In [96]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [98]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]], dtype=int32)

In [99]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]], dtype=int32)

In [103]:
l = [1, 2, 3, 4, 5, 6, 7]
l2 = l[:2:-1]
l2

[7, 6, 5, 4]

In [107]:
l2[0] = 77
l2

[77, 6, 5, 4]

In [108]:
l #결론 슬라이싱은 사본으로 한다

[1, 2, 3, 4, 5, 6, 7]

In [111]:
x2_1 = x2[::-1, ::-1]
x2_1

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]], dtype=int32)

In [112]:
x2_1[0, 0] = 99

In [116]:
print(x2_1,'\n',x2) #사본이 아니고 x2_1은 x2의 view를 제공하는 것

[[99  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5  3]] 
 [[ 3  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 99]]


In [118]:
#그럼 사본을 만들려면
x2_2 = x2[::-1, ::-1].copy()
x2_2

array([[99,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5,  3]], dtype=int32)

In [120]:
x2_2[0, 1] = 88
print(x2, '\n', x2_2)

[[ 3  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 99]] 
 [[99 88  6  1]
 [ 8  8  6  7]
 [ 4  2  5  3]]


In [127]:
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
grid = grid.reshape(3, 3) #((3, 3))이 정석
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
grid = grid.reshape(1, 9)
print(grid)
grid = grid.reshape(9, 1)
print(grid)

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [138]:
x = np.array([1, 2, 3])
x[np.newaxis, :]

array([[1, 2, 3]])